### ISSUE TITLE
Quick Question about Docker Containers monitor

### ISSUE THREAD

**Issue by mariushosting** [nicolargo/glances#2125] opened 2022-09-13 14:52 UTC
I just realized that glance 3.2.7 no longer does the docker container monitor. Did I miss something?

**Comment by bpgerber** [comment] 2022-09-14 14:12
I haven't had a container monitor for months. updated glances one day, no other changes and it was gone.

**Comment by igorrust** [comment] 2022-09-14 16:55
Same here, noticed it a few weeks ago. And just pulled the latest-full-tagged image of glances, but doesn't show the containers neither. :(

**Comment by nicolargo** [comment] 2022-09-15 06:48
Please all, fill the issue template correctly. We did not have any information concerning your operating system, the way you install Glances (container, os packaging, pip...). 

@igorrust i just try the latest docker images (nicolargo/glances:latest-full and nicolargo/glances:3.2.7-full) on my system and the Docker monitoring is ok.

**Comment by mariushosting** [comment] 2022-09-15 07:21
> Please all, fill the issue template correctly. We did not have any information concerning your operating system, the way you install Glances (container, os packaging, pip...).
> 
> @igorrust i just try the latest docker images (nicolargo/glances:latest-full and nicolargo/glances:3.2.7-full) on my system and the Docker monitoring is ok.

Device Synology NAS every device that support docker.
Guide followed and script here: https://mariushosting.com/how-to-install-glances-on-your-synology-nas/
Everything worked perfectly until version 3.2.5 with version 3.2.7 the docker container monitor is no longer displayed

**Comment by oystermon** [comment] 2022-09-28 23:58
I was having a similar problem (but probably from a version older than v3.2.5)

What worked for me was recreating the container, but using "nicolargo/glances:latest-full" instead of "nicolargo/glances:alpine-latest-full" as written in the frontpage.
So I think from your guide use what I mentioned above instead of "nicolargo/glances"

**Comment by mariushosting** [comment] 2022-09-29 00:24
nicolargo/glances:latest-full
did the trick!



> I was having a similar problem (but probably from a version older than v3.2.5)
> 
> What worked for me was recreating the container, but using "nicolargo/glances:latest-full" instead of "nicolargo/glances:alpine-latest-full" as written in the frontpage. So I think from your guide use what I mentioned above instead of "nicolargo/glances"
> 
> EDIT: basically what nicolargo suggested to do :)

**Comment by muuvmuuv** [comment] 2022-10-20 07:51
I am on macOS and tried it with pip and brew, both no Docker stats available. Docker is installed with VirtioFS and Compose v2.

**Comment by RazCrimson** [comment] 2023-05-12 19:35
Closing as the problem is fixed in newer releases

**Closed by RazCrimson** 2023-05-12 19:35 UTC
Labels: needs more info
