### ISSUE TITLE
Long commandline entry display in the next line

### ISSUE THREAD

**Issue by JanSchulz** [nicolargo/glances#744] opened 2015-12-06 14:24 UTC
This is a conda env py 3.5 on windows:
![2015-12-06_152302](https://cloud.githubusercontent.com/assets/890156/11613765/487d4404-9c2d-11e5-8b07-dbc8c2de638f.png)

```
[glances] λ conda env export
name: C:\portabel\miniconda\envs\glances
dependencies:
- cycler=0.9.0=py35_0
- jpeg=8d=vc14_0
- libpng=1.6.17=vc14_1
- libtiff=4.0.6=vc14_1
- matplotlib=1.5.0+532.g3d942f7.dirty=py35_0
- msvc_runtime=1.0.1=vc14_0
- numpy=1.10.1=py35_0
- openssl=1.0.2d=vc14_0
- pip=7.1.2=py35_0
- psutil=3.3.0=py35_0
- pyparsing=2.0.3=py35_0
- pyqt=4.11.4=py35_4
- python=3.5.0=4
- python-dateutil=2.4.2=py35_0
- pytz=2015.7=py35_0
- qt=4.8.7=vc14_5
- setuptools=18.5=py35_0
- sip=4.16.9=py35_2
- six=1.10.0=py35_0
- tk=8.5.18=vc14_0
- wheel=0.26.0=py35_1
- zlib=1.2.8=vc14_2
- pip:
  - colorconsole==0.7.2
  - glances==2.5.1
```

**Comment by nicolargo** [comment] 2015-12-07 15:28
@JanSchulz Looks like an colorconsole issue.

Can you try this command line:

    > glances --process-short-name

**Comment by JanSchulz** [comment] 2015-12-07 15:41
Unfortunately this doesn't make a difference :-(

Another interesting thing: if I right click (which does paste in cmder/ConEmu -> terminal app I use), I get a stacktrace:

```
Traceback (most recent call last):
  File "c:\portabel\miniconda\envs\glances\lib\site-packages\glances\outputs\glances_curses.py", line 692, in display
    self.glances_history.graph_enabled()
AttributeError: 'GlancesCursesStandalone' object has no attribute 'glances_history'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\portabel\miniconda\envs\glances\lib\runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\portabel\miniconda\envs\glances\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\portabel\miniconda\envs\glances\Scripts\glances.exe\__main__.py", line 9, in <module>
  File "c:\portabel\miniconda\envs\glances\lib\site-packages\glances\__init__.py", line 125, in main
    standalone.serve_forever()
  File "c:\portabel\miniconda\envs\glances\lib\site-packages\glances\core\glances_standalone.py", line 108, in serve_forever
    return self.__serve_forever()
  File "c:\portabel\miniconda\envs\glances\lib\site-packages\glances\core\glances_standalone.py", line 93, in __serve_forever
    self.screen.update(self.stats)
  File "c:\portabel\miniconda\envs\glances\lib\site-packages\glances\outputs\glances_curses.py", line 926, in update
    self.flush(stats, cs_status=cs_status)
  File "c:\portabel\miniconda\envs\glances\lib\site-packages\glances\outputs\glances_curses.py", line 892, in flush
    self.display(stats, cs_status=cs_status)
  File "c:\portabel\miniconda\envs\glances\lib\site-packages\glances\outputs\glances_curses.py", line 694, in display
    self.display_popup('History disabled\nEnable it using --enable-history')
  File "c:\portabel\miniconda\envs\glances\lib\site-packages\glances\outputs\glances_curses.py", line 752, in display_popup
    popup = curses.newwin(size_y, size_x, pos_y, pos_x)
AttributeError: 'WCurseLight' object has no attribute 'newwin'
```

And while trying to reproduce that:

```
Traceback (most recent call last):
  File "c:\portabel\miniconda\envs\glances\lib\runpy.py", line 170, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\portabel\miniconda\envs\glances\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\portabel\miniconda\envs\glances\Scripts\glances.exe\__main__.py", line 9, in <module>
  File "c:\portabel\miniconda\envs\glances\lib\site-packages\glances\__init__.py", line 125, in main
    standalone.serve_forever()
  File "c:\portabel\miniconda\envs\glances\lib\site-packages\glances\core\glances_standalone.py", line 108, in serve_forever
    return self.__serve_forever()
  File "c:\portabel\miniconda\envs\glances\lib\site-packages\glances\core\glances_standalone.py", line 93, in __serve_forever
    self.screen.update(self.stats)
  File "c:\portabel\miniconda\envs\glances\lib\site-packages\glances\outputs\glances_curses.py", line 914, in update
    self.flush(stats, cs_status=cs_status)
  File "c:\portabel\miniconda\envs\glances\lib\site-packages\glances\outputs\glances_curses.py", line 892, in flush
    self.display(stats, cs_status=cs_status)
  File "c:\portabel\miniconda\envs\glances\lib\site-packages\glances\outputs\glances_curses.py", line 502, in display
    'processlist').get_stats_display(args=self.args)
  File "c:\portabel\miniconda\envs\glances\lib\site-packages\glances\plugins\glances_plugin.py", line 551, in get_stats_display
    'msgdict': self.msg_curse(args),
  File "c:\portabel\miniconda\envs\glances\lib\site-packages\glances\plugins\glances_processlist.py", line 420, in msg_curse
    ret.extend(self.get_process_curses_data(p, first, args))
  File "c:\portabel\miniconda\envs\glances\lib\site-packages\glances\plugins\glances_processlist.py", line 365, in get_process_curses_data
    v = p['ionice'].ioclass
AttributeError: 'int' object has no attribute 'ioclass'
```

**Comment by nicolargo** [comment] 2016-02-26 14:26
Reproduce on my Windows testbed.

It is clearly a ColorConsole issue. Nevertheless, i am going to deprecate the Curse interface on the Windows console until Windows implement a "real" console mode with Curses support. Best way to use Glances on Windows is to run it in Web server mode:

    # glances -w

And start a Web Browser (http:\\<ip>:61208) to monitor your Windows machine...

**Comment by nicolargo** [comment] 2016-02-26 14:27
WONT FIX: Windows console  is a mess...

**Closed by nicolargo** 2016-02-26 14:26 UTC
Labels: bug

**Comment by asergi** [comment] 2016-02-26 18:24
```diff
diff --git a/glances/outputs/glances_curses.py b/glances/outputs/glances_curses.py
index b6d9ccf..1b65a99 100644
--- a/glances/outputs/glances_curses.py
+++ b/glances/outputs/glances_curses.py
@@ -21,6 +21,7 @@
 
 import re
 import sys
+import warnings
 
 from glances.compat import u
 from glances.globals import OSX, WINDOWS
@@ -40,6 +41,10 @@ if not WINDOWS:
             "Curses module not found. Glances cannot start in standalone mode.")
         sys.exit(1)
 else:
+    warnings.warn('Curses interface on Windows will be dropped. Please switch '
+                  'to web server mode as soon as possible. See '
+                  'https://github.com/nicolargo/glances/issues/744'
+                  ' for more information.')
     from glances.outputs.glances_colorconsole import WCurseLight
     curses = WCurseLight()
 
```
@nicolargo would be good as deprecation warning? What do you think?
