### ISSUE TITLE
Glances doesn't start on Debian 7.8 with python 3.2

### ISSUE THREAD

**Issue by primomh** [nicolargo/glances#524] opened 2015-03-09 18:08 UTC
Hello,

I try to install glances on my Debian 7.8 server. I installed python3.2 with the corresponding packages python3-dev and python3-pip.

I installed glances with pip and when I run glances, I have this result:
```
user@backup:/# glances
Traceback (most recent call last):
  File "/usr/local/bin/glances", line 9, in <module>
    load_entry_point('Glances==2.3', 'console_scripts', 'glances')()
  File "/usr/local/lib/python3.2/dist-packages/glances/__init__.py", line 119, in main
    args=core.get_args())
  File "/usr/local/lib/python3.2/dist-packages/glances/core/glances_standalone.py", line 62, in __init__
    self.stats.update()
  File "/usr/local/lib/python3.2/dist-packages/glances/core/glances_stats.py", line 156, in update
    self._plugins[p].update()
  File "/usr/local/lib/python3.2/dist-packages/glances/plugins/glances_plugin.py", line 639, in wrapper
    0].__class__.__module__[len('glances_'):], fct.func_name, ret))
AttributeError: 'function' object has no attribute 'func_name'
```

I see on your main page that glances 2.3 is tested with python 3.3 and 3.4. There are some known issues with python 3.2?

**Comment by asergi** [comment] 2015-03-10 11:03
We do not support Python >= 3.0, < 3.3.

Python 3.0-3.2 do not support unicode literal.

Reason for closing: Not a bug.

**Closed by asergi** 2015-03-10 11:03 UTC
