### ISSUE TITLE
Sensors Module missing value

### ISSUE THREAD

**Issue by WirthmU** [nicolargo/glances#2080] opened 2022-07-08 08:58 UTC
I am using glances with the "System" module installed.

sensors in the terminal gives me the following readout:
```
uw@uw-SBC-FITPC2:~/Scripts$ sensors
acpitz-virtual-0
Adapter: Virtual device
temp1:         +0.0°C  (crit = +127.0°C)
temp2:         +0.0°C  (crit = +95.0°C)

coretemp-isa-0000
Adapter: ISA adapter
Core 0:       +39.0°C  (crit = +90.0°C)
```

The sensors_acpitz_1 values in glances are correct (0), however the Core 0 temperature (sensors_Core_0.value) is wrong (52 instead of 39).

Any help to this?

**Comment by nicolargo** [comment] 2022-07-09 06:45
Not reproduced on my configuration.

I have a little gap between the Gmances and sensors value (~ 3°) because the refresh is not done at the same time.

Any other user reproduce the issue ?

**Comment by RazCrimson** [comment] 2023-04-23 13:27
Closing for now as its not reproducible on my end too.

If any other user encounter the problem, please comment here to re-open the issue.

**Closed by RazCrimson** 2023-04-23 13:27 UTC
Labels: needs more info
