### ISSUE TITLE
[snap] PermissionError: [Errno 13] Permission denied: '/proc/net/wireless'

### ISSUE THREAD

**Issue by gapplef** [nicolargo/glances#2829] opened 2024-06-11 02:00 UTC
**Environement (please complete the following information)**
 - Operating System (lsb_release -a or OS name/version): Ubuntu 24.04 LTS
 - Glances & psutil versions:  4.0.8  &  5.9.8
 - How do you install Glances (Pypi package, script, package manager, source): snap install
 - Glances test: 
```bash
Exception in thread Thread-30 (__update_plugin):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/snap/glances/1834/lib/python3.10/site-packages/glances/stats.py", line 258, in __update_plugin
    self._plugins[p].update()
  File "/snap/glances/1834/lib/python3.10/site-packages/glances/plugins/plugin/model.py", line 1151, in wrapper
    ret = fct(self, *args, **kw)
  File "/snap/glances/1834/lib/python3.10/site-packages/glances/plugins/plugin/model.py", line 1168, in wrapper
    ret = fct(*args, **kw)
  File "/snap/glances/1834/lib/python3.10/site-packages/glances/plugins/wifi/__init__.py", line 100, in update
    with open(WIRELESS_FILE) as f:
PermissionError: [Errno 13] Permission denied: '/proc/net/wireless'
===============================================================================
Glances 4.0.8 (/snap/glances/1834/lib/python3.10/site-packages/glances/__init__.py)
Python 3.10.12 (/snap/glances/1834/bin/python3)
PsUtil 5.9.8 (/snap/glances/1834/lib/python3.10/site-packages/psutil/__init__.py)
===============================================================================
alert         [OK]    0.00005s 
[]
amps          [OK]    0.00028s key=name 
[{'count': 0,
  'countmax': None,
  'countmin': 1.0,
  'key': 'name',
  'name': 'Dropbox',
  'refresh': 3.0,
  'regex': True,
  'result': None,
  'timer': 2.1051623821258545}, ...]
cloud         [NA]
connections   [NA]
containers    [OK]    0.00010s 
{}
core          [OK]    0.00184s 
{'log': 20, 'phys': 14}
cpu           [OK]    0.00075s 
{'cpucore': 20,
 'ctx_switches': 0,
 'ctx_switches_gauge': 3341567718,
 'guest': 0.0,
 'idle': 98.4,
 'interrupts': 0,
 'interrupts_gauge': 1875003394,
 'iowait': 0.0,
 'irq': 0.0,
 'nice': 0.0,
 'soft_interrupts': 0,
 'soft_interrupts_gauge': 367240074,
 'steal': 0.0,
 'syscalls': 0,
 'syscalls_gauge': 0,
 'system': 0.5,
 'time_since_update': 2.085129976272583,
 'total': 0.0,
 'user': 1.1}
diskio        [OK]    0.00016s 
[]
folders       [OK]    0.00004s 
[]
fs            [OK]    0.00037s 
[]
gpu           [OK]    0.00004s 
[]
help          [OK]    0.00001s 
None
ip            [OK]    0.00003s 
{}
irq           [NA]
load          [OK]    0.00006s 
{'cpucore': 20, 'min1': 0.37255859375, 'min15': 1.1201171875, 'min5': 0.85205078125}
mem           [OK]    0.00021s 
{'active': 12626751488,
 'available': 17895895040,
 'buffers': 1886339072,
 'cached': 17085382656,
 'free': 17895895040,
 'inactive': 10517311488,
 'percent': 46.4,
 'shared': 4984414208,
 'total': 33362857984,
 'used': 15466962944}
memswap       [OK]    0.00021s 
{'free': 8589930496,
 'percent': 0.0,
 'sin': 0,
 'sout': 0,
 'time_since_update': 2.0888800621032715,
 'total': 8589930496,
 'used': 0}
network       [OK]    0.00060s key=interface_name 
[{'alias': None,
  'bytes_all': 0,
  'bytes_all_gauge': 0,
  'bytes_all_rate_per_sec': 0.0,
  'bytes_recv': 0,
  'bytes_recv_gauge': 0,
  'bytes_recv_rate_per_sec': 0.0,
  'bytes_sent': 0,
  'bytes_sent_gauge': 0,
  'bytes_sent_rate_per_sec': 0.0,
  'interface_name': 'enp0s31f6',
  'key': 'interface_name',
  'speed': 0,
  'time_since_update': 2.009047269821167}, ...]
now           [OK]    0.00003s 
{'custom': '2024-06-11 09:58:53 CST', 'iso': '2024-06-11T09:58:53+08:00'}
percpu        [OK]    0.00005s key=cpu_number 
[{'cpu_number': 0,
  'guest': 0.0,
  'guest_nice': 0.0,
  'idle': 0.0,
  'iowait': 0.0,
  'irq': 0.0,
  'key': 'cpu_number',
  'nice': 0.0,
  'softirq': 0.0,
  'steal': 0.0,
  'system': 0.0,
  'total': 100.0,
  'user': 0.0}, ...]
ports         [OK]    0.00000s 
[]
processcount  [OK]    0.04165s 
{'pid_max': 0, 'running': 1, 'sleeping': 336, 'thread': 2592, 'total': 474}
processlist   [OK]    0.00012s 
[]
psutilversion [OK]    0.00002s 
'5.9.8'
quicklook     [OK]    0.00020s 
{'cpu': 0.0,
 'cpu_hz': 4400000000.0,
 'cpu_hz_current': 1623894200.0,
 'cpu_log_core': 20,
 'cpu_name': '13th Gen Intel(R) Core(TM) i7-13700H',
 'cpu_phys_core': 14,
 'load': 5.6,
 'mem': 46.4,
 'percpu': [{...}, {...}, {...}, {...}, {...}, {...}, {...}, {...}, {...}, {...}, {...}, {...}, {...}, {...}, {...},
            {...}, {...}, {...}, {...}, {...}],
 'swap': 0.0}
raid          [NA]
sensors       [OK]    0.00000s 
[]
smart         [NA]
system        [OK]    0.00000s 
{'hostname': 'joy',
 'hr_name': 'Ubuntu Core 22 64bit / Linux 6.8.0-35-generic',
 'linux_distro': 'Ubuntu Core 22',
 'os_name': 'Linux',
 'os_version': '6.8.0-35-generic',
 'platform': '64bit'}
uptime        [OK]    0.00008s 
{'seconds': 317041}
version       [OK]    0.00001s 
'4.0.8'
wifi          [ERROR] 0.00003s [Errno 13] Permission denied: '/proc/n
===============================================================================
Total time to update all stats: 0.04960s
===============================================================================
```

**Comment by nicolargo** [comment] 2024-06-14 13:42
For packager: perhaps have a look to: https://forum.snapcraft.io/t/snap-does-not-have-permission-to-use-stage-package/26621/3

For developer: catch the exception and generate a warning message

**Comment by nicolargo** [comment] 2024-06-15 06:45
Patch done in the develop branch for the "developer" part.

A new version of the Snapcraft packager is currently building with a new "network-setup-observe" that may solve this issue and perhaps another ones.

**Comment by nicolargo** [comment] 2024-06-15 06:59
@gapplef can you test the latest Snap version (4.0.8+build2) ?

**Comment by gapplef** [comment] 2024-06-15 09:23
After upgrade to 4.0.8+build2, the problem still exist.

**Comment by nicolargo** [comment] 2024-06-15 09:50
Damed...
So you had to wait the next Glances release (4.1.0).
I  the meanwhile disable the plugin.

Le sam. 15 juin 2024, 11:24, Julian Chen ***@***.***> a
écrit :

**Comment by gapplef** [comment] 2024-06-15 10:09
OK, still appreciate your work!

**Comment by RazCrimson** [comment] 2024-06-29 22:51
@gapplef 

Could you check if the issue is fixed now?

Glances has a release for 4.1.0+

**Comment by gapplef** [comment] 2024-07-01 01:27
Yes, the issue was fixed :tada:

**Comment by gapplef** [comment] 2024-07-01 01:37
Currently, the bottom left is left blank, missing `TCP connections`, `Disk I/O`, `File Sys`, `Sensors` compare to the official screenshot. Is this excepted?
![Screenshot from 2024-07-01 09-27-47](https://github.com/nicolargo/glances/assets/5604665/5215913d-a673-412c-a1ca-9b0cba9e6c99)

**Comment by RazCrimson** [comment] 2024-07-01 02:51
@nicolargo 

Are those plugins expected to work in snap?

**Comment by nicolargo** [comment] 2024-07-07 16:50
Message found into the log file:

```
/proc/diskstats" pid=4999 comm="python3" requested_mask="r" denied_mask="r" fsuid=1000 ouid=0
2024-07-07T16:44:55.526246+00:00 adapted-budgerigar kernel: audit: type=1400 audit(1720370695.523:1650): apparmor="DENIED" operation="open" class="file" profile="snap.glances.glances" name="/proc/4999/mounts" pid=4999 comm="python3" requested_mask="r" denied_mask="r" fsuid=1000 ouid=1000
2024-07-07T16:44:55.526276+00:00 adapted-budgerigar kernel: audit: type=1400 audit(1720370695.524:1651): apparmor="DENIED" operation="open" class="file" profile="snap.glances.glances" name="/proc/vmstat" pid=4999 comm="python3" requested_mask="r" denied_mask="r" fsuid=1000 ouid=0
2024-07-07T16:44:55.529746+00:00 adapted-budgerigar kernel: audit: type=1400 audit(1720370695.528:1652): apparmor="DENIED" operation="open" class="file" profile="snap.glances.glances" name="/proc/3/cmdline" pid=4999 comm="python3" requested_mask="r" denied_mask="r" fsuid=1000 ouid=0
2024-07-07T16:44:55.530222+00:00 adapted-budgerigar kernel: audit: type=1400 audit(1720370695.528:1653): apparmor="DENIED" operation="open" class="file" profile="snap.glances.glances" name="/proc/4/cmdline" pid=4999 comm="python3" requested_mask="r" denied_mask="r" fsuid=1000 ouid=0
```

Strange because [system-observe](https://snapcraft.io/docs/system-observe-interface) is configure as a plugin and should give read access to all the system... But snap is snap... a pain in the ass.

**Closed** 2024-08-24 08:39 UTC
Labels: packaging, needs test
