### ISSUE TITLE
Glances crashes in client mode on windows silently

### ISSUE THREAD

**Issue by SpiGAndromeda** [nicolargo/glances#1016] opened 2017-02-01 05:49 UTC
#### Description

Glances crashes in client mode immediately on Windows 10. Server is running on an Ubuntu Server machine. There are no logs on the server. Firewall is disabled and removed. Same problem. Ports are opened via ufw on ubuntu. Glances is able to start in server mode and web-server mode on windows. Starting server mode and connecting via another cmd in client mode to the local server results in the same crash on windows.

#### Versions

* Glances v2.8 with psutil v5.0.0
* Windows 10 64Bit

#### Logs on client (created in debug mode)

2017-02-01 06:42:35,309 -- INFO -- Start Glances 2.8
2017-02-01 06:42:35,309 -- INFO -- CPython 3.6.0 and PSutil 5.0.0 detected

**Comment by nicolargo** [comment] 2017-02-02 12:09
Can you try Glances in debug mode (-d) and paste/bin us the log file.

Thanks.

**Comment by SpiGAndromeda** [comment] 2017-02-02 12:13
This already was debug mode.

**Comment by nicolargo** [comment] 2017-02-02 12:16
You said that Glances crash. What is the error message ?

**Comment by SpiGAndromeda** [comment] 2017-02-03 10:12
There was no. I starts, you can see that the name of the window in the title bar changes for a second to "python -m glances -c ...". The it returns to the original state and cmd jumps to the next line for input.

**Comment by Argasm** [comment] 2017-03-09 20:19
I have exactly the same pb here.
Glances 2.8.2
psutil 5.1.3
windows 10 64 
I'll test with a win7 vm and keep you informed

**Comment by nicolargo** [comment] 2017-03-10 21:09
Any heads up ?

**Comment by Argasm** [comment] 2017-03-13 17:46
Hi,
Sorry, i had to reinstall my comp because of a conflict between docker and virtualbox. Docker refused to uninstall and caused virtualbox to crash.

Since the reinstallation, glances works well

My old windows 10 was installed as an upgrade of a windows 8. Since it's not wise to do it may be the root of the problem. I'll try to reproduce the bug with vm again and keep you tuned.

**Comment by nicolargo** [comment] 2017-03-18 08:04
Ok thanks, i close the issue. Please feel free to re-open it if the problem came back.

**Closed by nicolargo** 2017-03-18 08:04 UTC
Labels: needs more info
