### ISSUE TITLE
Incorrect Core count

### ISSUE THREAD

**Issue by etacalpha** [nicolargo/glances#1604] opened 2020-02-18 17:24 UTC
#### Description
Core Count for Load is showing 1-core

CPU is a Ryzen 9 with 12 hyper-threaded cores

#### Versions
Glances: v3.1.3 with psutil v5.6.7
OS: Manjaro-KDE
Linux Kernel: 5.4.18

![glances](https://user-images.githubusercontent.com/18453591/74761062-5e83af00-5249-11ea-9f6e-6ff3ae8db398.png)

**Comment by nicolargo** [comment] 2020-02-27 13:11
Hi @etacalpha 

sorry for the delay.

Glances uses the PsUtil lib to grab core number.

Can you please copy paste the result of the following command:

    python -c "import psutil; print(psutil.cpu_count(logical=False)); print(psutil.cpu_count())"

Thanks !

**Comment by etacalpha** [comment] 2020-02-27 13:13
Sure
```
12
24
```

**Comment by nicolargo** [comment] 2020-02-27 13:35
Strange...

I just commit a patch with a debug message. Can you test the DEVELOP branch on your system ([see procedure here](https://github.com/nicolargo/glances/wiki/Install-and-test-Glances-DEVELOP-version)) and run Glancesin debug mode (-d) and finally pastebin us the Glances log file.

Thanks.

**Comment by etacalpha** [comment] 2020-02-27 14:03
I will, it will be this evening before I can complete it.

**Comment by nicolargo** [comment] 2020-03-03 21:38
@etacalpha Any update ?

**Comment by etacalpha** [comment] 2020-03-04 00:58
I apologize for taking so long. I am having issues getting the development branch to run. I can't follow the instructions very well as the packages do not exist for arch based distros as well as I am using pyenv-virtualenv. I haven't had a lot of time to work around the above. I have noticed that both TOP and HTOP have the same issue though.

**Comment by etacalpha** [comment] 2020-03-04 12:44
[glances-sbeard.log](https://github.com/nicolargo/glances/files/4287296/glances-sbeard.log)

Still working on getting the development version running.

**Comment by nicolargo** [comment] 2020-03-10 20:29
It is more an operating system issue than a Glances issue...

The system return 1 when Glances ask for core number.

Any chance to upgrade the OS Kernel ?

**Comment by veox** [comment] 2020-03-25 18:52
I've been getting the same for a while now, also on Arch Linux.

I'm on the 5.5.x kernel branch (v5.5.10 ATM), and it has the same behaviour.

However, checking out `develop` (at 6f284cc97aa40d080976d0f43a918680574178cf) and running that does not show the bug.

**Comment by veox** [comment] 2020-03-25 19:12
OK, so I've checked out locally v3.1.3 (same as in [latest Arch package](https://www.archlinux.org/packages/community/any/glances/) ATM), and the issue is there.

I've then checked out v3.1.4.1 (recommended as latest stable), and the issue is not there.

IMO this can be closed as "not present in current stable or development".

**Comment by veox** [comment] 2020-04-28 18:51
Glances v3.1.4.1 package is [now in ArchLinux](https://www.archlinux.org/packages/community/any/glances/).

The issue, as expected, is gone.

([Not yet in Manjaro](https://discover.manjaro.org/packages/glances), though.)

@nicolargo - there is no actionable here, it's up to distro packagers to update.

**Comment by nicolargo** [comment] 2020-04-29 07:32
Thanks for the feedback @veox

**Comment by nicolargo** [comment] 2020-04-29 07:33
Corrected in version 3.1.4.1 or higher.

**Closed by nicolargo** 2020-04-29 07:33 UTC
Labels: bug, needs more info
