### ISSUE TITLE
Docker: Bottle module not found. Glances cannot start in web server mode

### ISSUE THREAD

**Issue by Timi7007** [nicolargo/glances#2155] opened 2022-10-16 23:21 UTC
I just updated my Docker container for Glances on Unraid and it appears #1017 is back as of today:
```nicolargo/glances:latest``` (default on Unraid) throws ```Bottle module not found. Glances cannot start in web server mode.``` in the log-file while the container just stops. ```nicolargo/glances:3.3.0-full``` does not have this issue and starts just fine.

```nicolargo/glances:3.3.0``` has the issue.
```nicolargo/glances:3.2.7``` does not have it.
```nicolargo/glances:latest-full``` works.
I have not tested any Alpine-based versions.

I'm unsure if this is intended. Is the web-UI meant for non-"full"-versions? If so this is a breaking change between 3.2.7 and 3.3.0. If not we might have to change Unraid's default for Glances to ```nicolargo/glances:latest-full```.

Side note: _Unraid has trouble recognizing tags ending in numbers and says it can't find the repository. But it does, so everything still works, it just shows up wrong. (E.g. ```nicolargo/glances:3.2.7``` and ```nicolargo/glances:3.3.0```, while "latest", "latest-full" and "*-full" are displayed correctly.)
This somewhat cosmetic issue seems to be caused by Unraid, though._

**Comment by TadMSTR** [comment] 2022-10-17 01:21
I can confirm `nicolargo/glances:alpine-latest-full` works as I just tried it after I got the same issue with the default tag.

**Comment by haeihaiehaei** [comment] 2022-10-17 12:45
Hi, had the same issue on my dietPi server, installing the module works fine. 
`pip install bottle`

**Comment by RynoM** [comment] 2022-10-17 15:07
Same issue here

**Comment by silvannn** [comment] 2022-10-17 15:28
I have the same error. Glances are stopped. My knowledge is too poor to fix it. I had removed and installed again. Did not help.

**Comment by fahrenhe1t** [comment] 2022-10-17 19:47
Receiving this error after updating the glances:latest container on a home server (so not limited to Unraid).  I would prefer not to install this Bottle python component on bare metal, since that defeats the purpose of containerization.

**Comment by nicolargo** [comment] 2022-10-17 21:25
Hi all, 

sorry for the issue, by "minimal" i mean minimal (without bottle). I understand that most of the time Glances containers is used with the WebUI so i just push a new version with bottle in the minimal images. The build is ongoing, will be available in 1 hour.
Target version: **3.3.0.1**.


Nicolas

**Comment by TadMSTR** [comment] 2022-10-17 22:02
> I have the same error. Glances are stopped. My knowledge is too poor to fix it. I had removed and installed again. Did not help. Unraid.

Just change the tag in the container template to one that was listed as working. so any of the full tags should be fine.

**Comment by boehser-enkel** [comment] 2022-10-18 05:15
> Hi all,
> 
> sorry for the issue, by "minimal" i mean minimal (without bottle). I understand that most of the time Glances containers is used with the WebUI so i just push a new version with bottle in the minimal images. The build is ongoing, will be available in 1 hour. Target version: **3.3.0.1**.
> 
> Nicolas

Works again. Thank you

**Comment by boehser-enkel** [comment] 2022-10-18 05:58
But with new problems:
![grafik](https://user-images.githubusercontent.com/59539881/196347467-462cba0b-5ccb-4d8e-ad05-f765ee840ab0.png)

**Comment by RazCrimson** [comment] 2023-03-18 09:23
Closing as a patch was released to fix this.

@boehser-enkel 
Please open a newer ticket in case you face the newly mentioned issues even with the latest release.

**Closed by RazCrimson** 2023-03-18 09:23 UTC
Labels: packaging
