### ISSUE TITLE
Binary highlighting in TASKS-list is incorrect when path contains whitespaces

### ISSUE THREAD

**Issue by lxsndl** [nicolargo/glances#546] opened 2015-04-24 08:48 UTC
On OSX the green highlighting of the binary in the task list does not properly handle white spaces in the path e.g.

> /Applications/**Google** Chrome.app/Contents/MacOS/Google Chrome

expected behaviour would be

> /Applications/Google Chrome.app/Contents/MacOS/**Google Chrome**

(bold should be highlighted)

it's really not high priority just something I noticed.

**Comment by desbma** [comment] 2015-05-10 02:27
Reproduced in Ubuntu, with a program whose path is '/tmp/a b', generated with :
`echo "int main() { while(1) sleep(1); }" | gcc -x c - -o '/tmp/a b'`

In theory, this patch should do the trick :

    diff --git a/glances/plugins/glances_processlist.py b/glances/plugins/glances_processlist.py
    index 341ba88..43b47f4 100644
    --- a/glances/plugins/glances_processlist.py
    +++ b/glances/plugins/glances_processlist.py
    @@ -285,11 +285,9 @@ class Plugin(GlancesPlugin):
                 ret.append(self.curse_add_line(msg, splittable=True))
             else:
                 try:
    -                cmd = cmdline.split()[0]
    -                argument = ' '.join(cmdline.split()[1:])
    -                path, basename = os.path.split(cmd)
    +                path, basename, argument = map(str.strip, cmdline.partition(p['name']))
                     if os.path.isdir(path):
    -                    msg = ' {0}'.format(path) + os.sep
    +                    msg = ' {0}'.format(path)
                         ret.append(self.curse_add_line(msg, splittable=True))
                         ret.append(self.curse_add_line(basename, decoration='PROCESS', splittable=True))
                     else:

However psutil has a bug, because it tries to be clever in process.name() and return the end of the command line in some cases (see https://pythonhosted.org/psutil/_modules/psutil.html#Process.name), as a consequence it does not actually return the name in the above test case.

**Comment by nicolargo** [comment] 2015-06-02 17:35
@desbma What do you think ? Postpone until the PsUtil bug correction ?

**Comment by desbma** [comment] 2015-06-02 18:09
It's clearly a psutil bug, but I did not check if there is already an open ticket about it. 

But yeah this needs to be fixed in psutil, we don't want to add a workaround against what is already a workaround.

**Comment by nicolargo** [comment] 2015-06-02 18:14
Ok, postpone to another release.
Nevertheless, i am not sure that PsUtil considers the trucate name as a bug...

**Comment by desbma** [comment] 2015-06-02 18:45
I've created an issue in psutil

**Comment by asergi** [comment] 2015-06-02 23:34
About @desbma proposal:

It might seem a good idea at first glance but there are two main problems:

- using `partition` will only split the string at the first occurrence of the given argument (the process name). So the above example will be:

> /Applications/**Google Chrome**.app/Contents/MacOS/Google Chrome

Imo, that would be good as well.

- process name as sentinel: it becomes a problem when the it appears more than once in the full cmdline. For instance:

> **glances** /bin/python3.4 /home/alessio/venvs/py34-glances/bin/glances
> /home/alessio/venvs/py34-**glances** /bin/python3.4 /home/alessio/venvs/py34-glances/bin/glances

The correct cmdline:
> /home/alessio/venvs/py34-glances/bin/python3.4 /home/alessio/venvs/py34-glances/bin/glances

---
Agree with @nicolargo, I don't think that psutil would consider the truncated name a bug.

For the record: the current highlighting implementation is not based on the process name, so the psutil bug may not be related.

**Comment by desbma** [comment] 2015-06-03 18:36
> It might seem a good idea at first glance but there are two main problems:

You are right it's not perfect.

Ideally we should use `process.exe()` but it tried other approaches with it and there are always some corner cases where that fails.
For example when starting Python in a venv, `cmdline` starts with `python` but `exe` starts with `python3.4`...

There is also the fact that some platforms return empty strings for some of theses, and we have no unit tests to check if we break something...

> FYI: the current highlighting implementation is not based on the process name, so that psutil bug may not be related.

I know but my patch did use p['name'] and so does the code now in the develop branch.

Anyway it'll be a bit better now that the psutil bug got fixed.

**Comment by asergi** [comment] 2015-06-04 14:25
> I know but my patch did use p['name'] and so does the code now in the develop branch.

The process name is only used when the cmdline is not available or you want to display it explicitly. Even in the develop branch.

I took the inspiration for this approach from htop. It's a path-based solution. More reliable and less headache, imo.

**Comment by nicolargo** [comment] 2016-01-26 21:21
Waiting for a patch.

**Comment by desbma** [comment] 2016-01-26 22:37
OK so I believe I have fixed all regressions [mentioned by @asergi](https://github.com/nicolargo/glances/pull/786#issuecomment-174957529), except maybe the last one (I have not reproduced).

However in the process I exposed another Psutil bug, and I just opened an [issue](https://github.com/giampaolo/psutil/issues/742).

So I will submit a new pull request to revert my last changes, and when the Psutil bug is fixed, create a new pull request with all the fixes to (hopefully) fix once and for all this issue.

Meanwhile if any of you has some time, you can try the code in my [issue546](https://github.com/desbma/glances/tree/issue546) branch and check everything works fine (excluding the Psutil bug).

**Comment by nicolargo** [comment] 2016-01-27 08:46
@asergi Can you have a lok on the @desbma https://github.com/desbma/glances/tree/issue546 branch ?

**Comment by asergi** [comment] 2016-01-27 18:40
I have prepared a patch to "resolve" this issue. I'll post it shortly after testing.

**Comment by asergi** [comment] 2016-01-28 11:31
Patch: https://gist.github.com/asergi/a62ec884baf6d715ecaa

It's very simple but gets its job done. Tested on Linux, FreeBSD and Windows successfully.

psutil already returns the command line splitted as a list, where the first item always contains the process name (with or without path). So, it's much easier working on the list rather then threating it as a string.

The only drawback is that the behaviour of psutil is not the same across the OSes. In fact, if no command line is available, it returns an empy list (correct) on Windows, while on Linux and FreeBSD (and OS X too?) returns [''].

While I was here, I fixed the not so common case where the command line contains line breaks (\n).

Anyway, please test. It would be nice if someone could test it on OS X, too.

**Comment by desbma** [comment] 2016-01-28 21:12
@asergi I have tested your patch and it works well in my case (Ubuntu), but because it uses the `name` attribute from psutil processes, it also affected by [the bug I mentioned](https://github.com/giampaolo/psutil/issues/742).

See the wrong highlighting:
![Imgur](http://i.imgur.com/LCDlCrq.png)

**Comment by asergi** [comment] 2016-02-22 12:16
The bug I have mentioned in my previous comment has been fixed in psutil 4.0.0.

That said, the patch doesn't change because we have to maintain compatibility with psutil releases < 4.0.0. The same goes for the bug mentioned by @desbma (when will be fixed, and it only affects the chromium process).

So, I believe the patch can be safely applied.

**Comment by nicolargo** [comment] 2016-02-26 13:24
@asergi Is the patch as been applied ?

**Comment by asergi** [comment] 2016-02-26 18:13
Not yet. Will do soon.

**Comment by nicolargo** [comment] 2016-03-06 15:16
Hi @asergi , i want to release Glances 2.6 during the next week. Can you apply the patch (or i can do it on my side if you did not have time).

**Comment by asergi** [comment] 2016-03-06 18:12
Done.

**Comment by nicolargo** [comment] 2016-03-11 12:20
Perfect ! Thks @asergi

**Closed by nicolargo** 2016-03-11 12:20 UTC
Labels: bug
