### ISSUE TITLE
Export individual processes stats

### ISSUE THREAD

**Issue by lawre** [nicolargo/glances#794] opened 2016-02-20 14:52 UTC
I would really like some way to export the individual process metrics to influxdb so we can better pinpoint what process is hogging our memory, network or cpu and for how long.  I work in a software build environment, so these kinds of metrics can really help nail down bottlenecks in a jenkins build.

**Comment by nicolargo** [comment] 2016-02-20 18:08
It is a good idea but... how to identify the process (primary key) ?
1) PID ?
2) Command line ?
3) Process name ?

**Comment by lawre** [comment] 2016-02-21 14:12
My primary goal for this request is to be able to hover over a line in a grafana graph and a tooltip will pop up with the full command line of the process I'm interested in.  How can this best be accomplished?

primary = PID: This would be a good choice if we can figure out how to get Grafana to tooltip a second field instead of the one we're querying on.  I'm not so interested in the PID per se, but it does offer the convenience of guaranteeing uniqueness for each process.

primary = Command Line: I think this would be the most straight-forward approach.  But these lines can get pretty long with lots of funny characters.  Can InfluxDB handle this?  Perhaps truncate at # of characters?  This approach also leaves the danger of a program like apache spawning multiple processes for the same thing... these wouldn't look unique in this case.

primary = PID-Command Line: Concatenating the PID and the command line might be the best approach to guarantee uniqueness if we can't figure out the tooltip shows secondary info problem.

primary = command: This does not get granular enough for me.  Think of the Apache web server, or in my case the Jenkins node allowing simultaneous runs. 

Thank you for considering this feature!

**Comment by wingsof** [comment] 2016-02-23 00:56
Wow! I also need this feature!
My purpose is to capture load of specific processes while running stress test on several solutions. I think only nmon currently exports this information.

Regarding primary key, I think combination of pid and start time of the process (because of pid reuse) might be enough to uniquely identify process.

**Comment by johnhill2** [comment] 2016-02-23 01:08
My team desperately needs this feature too. I've had to do some crazy stuff with the per process utilization flat file and rsync. Having it export directly to influxdb is our number one feature request

**Comment by gabrieljames** [comment] 2016-03-01 14:15
+1 

I've been working my way through the data collection agents (collectd, telegraf, topbeat) and have been completely surprised, shocked, that none of these agents collect all process cpu, mem and disk metrics. Some will allow specific process monitors to be defined in configuration files, but i'm looking for comprehensive process monitoring metrics stored in Influx or Logstash.  

Hate to say it, but this is straight forward in Windows performance logging.

I am about to test Glances specifically for this capability, was expecting it to be there based on the data displayed in the command line interface

**Comment by nicolargo** [comment] 2016-03-04 08:23
@lawre Another approch: use the PID as primary key and use tags to store: process name, full command line, process start...

What do you think ?

**Comment by johnhill2** [comment] 2016-03-11 23:25
@nicolargo that will work for me

**Comment by lawre** [comment] 2016-05-11 22:18
I think that would work, good suggestion.

**Comment by nicolargo** [comment] 2016-07-06 08:40
My proposal to use the PID as primary key and store the process name, command line in tags only work for InfluxDB, the current architecture of the Glances export module is not related to the storage database (for example, same function are used to store in CSV, InfluxDB or Cassandra...). Tags only exist in the InfluxDB ecosystem.

Two others points to keep in mind:
- for the moment, the Glances process list is optimized. It grabs cpu_percent, memory_percent, io_counters, name, cmdline for all processes (it's called mandatory stats) and others stats (extended stats) only for processes displayed in the UI. Export will only be done on mandatory stats.
- performance issue can occur while writting hude process list to the database

*My new proposal*: define a processes list (for example using regular expression on command line), only the filtered process will be exported. 

For example, if you want to monitor the NGinx process:
```
[export_processes]
foonginx=^nginx.*
```

The key is foonginx. It will export all the mandatory stats for the processes command line starting with nginx (one line per process or one line for all the processes, to be discus). 

What do you think ?

**Comment by nicolargo** [comment] 2016-07-18 19:31
@lawre : Any head up concerning my last proposal ?

**Comment by lawre** [comment] 2016-07-18 22:02
Sorry, I didn't see the alert for your question before. 

collectd's processes plugin already allows for regex match of processes, so in our case we would just continue to use that.  Is there a possibility for this just to be an "InfluxDB only" feature as it is probably the only uniquely qualified database for this type of data?  I'm not sure any other fixed key DB would even be able to handle this.  I couldn't imagine reading it in a CSV where there could be 20-100 ever changing PIDs to key off.

**Comment by nicolargo** [comment] 2016-12-11 16:42
I just try to code a first version in a local branch. The main problem is that the process stats update is done asynchronously in a specific thread. So when the stats are exported we are not sure that the process stats are completed. One workaround is to force the update before the export. But it cost a lot of CPU consumption...

**Comment by nicolargo** [comment] 2017-08-12 12:34
Will be implemented in Glances version 3.0 (after the complete code refactor and change of the software architecture).

**Comment by nicolargo** [comment] 2018-02-25 12:57
No time to work on this request for Glances 3.0. Need contributor !

**Comment by unlikelyzero** [comment] 2023-12-12 15:40
For now, I'm going to be using a combination of https://github.com/ncabatoff/process-exporter and glances (container and gpu measurement). Ideally, I'd route all of this through the grafana agent to make a single target in prometheus.

**Comment by nicolargo** [comment] 2024-04-02 09:19
Feature previous implemented in the branch: https://github.com/nicolargo/glances/tree/issue794

The processes list to exprt should be defined in the Glances configuration file:

```
#
# Define the list of processes to export using:
# a comma-separated list of regular expression (apply on name and cmdline)
export=.*firefox.*
# or an uniq key:value filter
#export=pid:1234
```

**Comment by nicolargo** [comment] 2024-04-06 15:51
Feature merged into develop.

The documentation is here: https://github.com/nicolargo/glances/blob/develop/docs/aoa/ps.rst#export-process

Need beta testers on this feature !

cc: @unlikelyzero @gotjoshua @lawre @johnhill2 @gabrieljames @wingsof

**Comment by bLuka** [comment] 2024-04-18 00:51
What a great day to be alive! I’ve been looking for such a feature for years, it’s been ages I haven’t touched Glances, and I just redid my monitoring setup over Glances + InfluxDB + Grafana past few days.
Just to learn my long-awaited feature have been implemented 2 weeks ago ❤️ 

I deployed upstream’s develop Glances over my server, and process exporter works like a charm! I see data coming to InfluxDB and rendered on Grafana already. I don’t see anything wrong there, I’ll keep you updated if you want to confirm it’s stable on the long run.

I’m wondering (as I’m investigating disks I/O bottlenecks from unmonitored processes), is there any reason per-process disk I/O metrics are not exported?
I am talking about [the bytes `R/s` and `W/s` metrics which are already present in the curses display](https://github.com/nicolargo/glances/blob/develop/docs/aoa/ps.rst#columns-display).

**Comment by bLuka** [comment] 2024-04-21 02:20
I find the cardinality a bit odd (and difficulte to manipulate subsequently).
Is there specific reasons/constraints that require an export such as:

| timestamp           | 821811.num_threads | 821811.name       | 821811.cpu_timesuser | 2950324.num_threads | 2950324.name       | 2950324.cpu_timesuser |
|---|---|---|---|---|---|---|
| N |  1                  | kworker/13:5-events| 0.02                  |  22                  | dotnet | 233.79                  |
| N+1 |  1                  | kworker/13:5-events| 0.02                  |  22                  | dotnet | 233.79                  |


Instead of a format with 1 row per process and fewer columns? Such as:
| timestamp | pid     | num_threads | name               | cpu_timesuser |
|-----------|---------|-------------|--------------------|---------------|
| N         | 821811  | 1           | kworker/13:5-events| 0.02          |
| N         | 2950324 | 22          | dotnet             | 233.79        |
| N+1       | 821811  | 1           | kworker/13:5-events| 0.02          |
| N+1       | 2950324 | 22          | dotnet             | 233.79        |


I’m currently struggling to parse the results to build a Grafana dashboard from the InfluxDB backend, and the latter format would make it easier.

Additionally, regarding the format, I noticed a weird behavior where the processes were not aligned in the proper columns:
<img width="695" alt="image" src="https://github.com/nicolargo/glances/assets/36578146/ed228a18-f842-417a-80f0-a38d5d623a0d">

I reproduce consistently using the following command (and my own process list which includes a lot of processes):
```
glances -C --export csv --export-csv-file /tmp/glances.csv  --export-process-filter ".*dotnet.*,*java*,*qemu*,*samba*,*lxd*,*docker*" --disable-plugin all --enable-plugin processlist --quiet
```

I’m wondering if it comes from the fact that I monitor a lot of processes (some of which terminate, other spawn)?

**Comment by nicolargo** [comment] 2024-04-21 16:33
Hi @bLuka and thanks for the feedback.

Concerning the CSV export, i want to keep one line per timestamp because the header should be the same for each line.  
This behavior is also used for others plugins like network, where stats are displayed with the following format: <interface>.<stats>. However, the weird behavior concerning the column are not "normal". But i think that i understand what happen. If one of your process die during the capture then the column can be overwritten by another stats. had to investigate this...

For the InfluxDB export, this is not the same behavior and all the stats are exported line by line, the pid become a tag (in the InfluxDB data model). I just add the process name has another tag. So it should simplify the way InfluxDB store the information and so also simplify Grafana dashboard creation.

**Comment by guidocioni** [comment] 2024-04-25 08:49
Hey all. I've been testing also this feature, so I'll report here in the future in case I have some feedback. 

Just a quick question. Is there any way to export in the csv only the N (user defined) processes with the highest CPU usage? Or the only way to filter what is saved in the CSV (or anything else) is the process filter with regular expression? I guess it would be hard to have PIDs changing at every timestamp as the schema of the table exported is defined at the beginning.

**Comment by nicolargo** [comment] 2024-04-26 07:39
@guidocioni For the moment it is not possible but it is a nice feature. Can you open a new issue ?

Thanks !

**Closed by nicolargo** 2024-04-26 07:39 UTC
Labels: new feature, needs discussion, needs test
