### ISSUE TITLE
InfluxDB2 export mode crashes with debug log msg "Cannot export empty wifi stats to InfluxDB"

### ISSUE THREAD

**Issue by gojun077** [nicolargo/glances#2342] opened 2023-04-13 12:47 UTC
**Describe the bug**
When launching glances with `glances --export influxdb2` I am getting the following stacktrace:

```
File "/home/jundora/.local/lib/python3.11/site-packages/glances/plugins/glances_raid.py", line 96, in msg_curse
self.stats[array]['status'],
~~~~~~~~~~~~~~~~~^^^^^^^^^^
TypeError: 'float' object is not subscriptable
```

**To Reproduce**
1. Start Glances with the following options '--export influxdb2'
2. glances will crash with a stack trace within 5s
3. See error

**Expected behavior**
I installed `glances` and `influxdb-client` (the new client for influxdb2) and have a working influxdb2 instance. In my `glances.conf` I have specified the influxdb hostname which is reachable on TCP 8086 via https and also included a token which has the rights to r/w to the *glances* bucket.
When I run `glances` without exporting to influxdb2, glances is working normally with no crashes.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Fedora 37
   + uname output: `Linux argonaut 6.2.9-200.fc37.x86_64 #1 SMP PREEMPT_DYNAMIC Thu Mar 30 22:31:57 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux`
 - Glances Version

```
Glances v3.3.1.1 with PsUtil v5.9.1
Log file: /home/jundora/.local/share/glances/glances.log
``` 

 - Glances logs file [output of tail -10 <glances logs file>] (I ran `glances -d --export influxdb2` for debug mode logging)

```
...
2023-04-13 21:44:47,396 -- DEBUG -- Export mem stats to InfluxDB
2023-04-13 21:44:47,396 -- DEBUG -- Export memswap stats to InfluxDB
2023-04-13 21:44:47,397 -- DEBUG -- Export network stats to InfluxDB
2023-04-13 21:44:47,398 -- DEBUG -- Export percpu stats to InfluxDB
2023-04-13 21:44:47,400 -- DEBUG -- Export processcount stats to InfluxDB
2023-04-13 21:44:47,400 -- DEBUG -- Export raid stats to InfluxDB
2023-04-13 21:44:47,401 -- DEBUG -- Export sensors stats to InfluxDB
2023-04-13 21:44:47,401 -- DEBUG -- Export system stats to InfluxDB
2023-04-13 21:44:47,401 -- DEBUG -- Export uptime stats to InfluxDB
2023-04-13 21:44:47,401 -- DEBUG -- Cannot export empty wifi stats to InfluxDB
```

 - Glances test [output of glances --issue] (only available with Glances 3.1.7 or higher)

```
=======================================================================================================================
Glances 3.3.1.1 (/home/jundora/.local/lib/python3.11/site-packages/glances/__init__.py)
Python 3.11.2 (/usr/bin/python3)
PsUtil 5.9.1 (/usr/lib64/python3.11/site-packages/psutil/__init__.py)
=======================================================================================================================
alert         [OK]    0.00003s []
amps          [OK]    0.00009s []
cloud         [OK]    0.00006s {}
connections   [OK]    0.01599s {'LISTEN': 15, 'ESTABLISHED': 28, 'SYN_SENT': 1, 'SYN_RECV': 0, 'initiated': 1
core          [OK]    0.00094s {'phys': 6, 'log': 12}
cpu           [OK]    0.00049s {'total': 6.7, 'user': 0.2, 'nice': 0.0, 'system': 0.2, 'idle': 98.9, 'iowait'
diskio        [OK]    0.00081s key=disk_name [{'time_since_update': 2.219820737838745, 'disk_name': 'sda', 'r
docker        [OK]    0.00004s []
folders       [OK]    0.00003s []
fs            [OK]    0.00092s key=mnt_point [{'device_name': '/dev/mapper/fedora-00', 'fs_type': 'xfs', 'mnt
gpu           [OK]    0.00003s []
help          [OK]    0.00001s None
ip            [OK]    0.00005s {}
irq           [OK]    0.00108s key=irq_line [{'irq_line': 'LOC', 'irq_rate': 1207, 'key': 'irq_line', 'time_s
load          [OK]    0.00006s {'min1': 0.0, 'min5': 0.0, 'min15': 0.0, 'cpucore': 12}
mem           [OK]    0.00024s {'total': 29281587200, 'available': 26983550976, 'percent': 7.8, 'used': 22980
memswap       [OK]    0.00031s {'total': 8589930496, 'used': 0, 'free': 8589930496, 'percent': 0.0, 'sin': 0,
network       [OK]    0.00090s key=interface_name [{'interface_name': 'lo', 'alias': None, 'time_since_update
now           [OK]    0.00002s 2023-04-13 21:29:04 KST
percpu        [OK]    0.00016s key=cpu_number [{'key': 'cpu_number', 'cpu_number': 0, 'total': 72.0, 'user':
ports         [OK]    0.00036s []
processcount  [OK]    0.04266s {'total': 314, 'running': 1, 'sleeping': 189, 'thread': 684, 'pid_max': 0}
processlist   [OK]    0.00013s key=pid [{'gids': pgids(real=1000, effective=1000, saved=1000), 'memory_info':
psutilversion [OK]    0.00002s (5, 9, 1)
quicklook     [OK]    0.00020s {'cpu': 6.7, 'percpu': [{'key': 'cpu_number', 'cpu_number': 0, 'total': 72.0,
raid          [OK]    0.00001s {}
sensors       [OK]    0.00000s key=label [{'label': 'Composite', 'unit': 'C', 'value': 32, 'warning': 69, 'cr
smart         [NA]
system        [OK]    0.00000s {'os_name': 'Linux', 'hostname': 'argonaut', 'platform': '64bit', 'linux_distr
uptime        [OK]    0.00005s {'seconds': 48521}
wifi          [OK]    0.00001s []
=======================================================================================================================
Total time to update all stats: 0.06852s
=======================================================================================================================
```

**Additional context**
This error occurs only in influxdb2 export mode; when glances in run standalone, I have not experienced any crashes

**Comment by RazCrimson** [comment] 2023-04-13 17:34
Closing as this should be a duplicate of #2297 which has already been fixed

The fix should be available from the next release (3.4.0)

**Closed by RazCrimson** 2023-04-13 17:34 UTC
Labels: duplicated
