### ISSUE TITLE
Glances no longer starts on Unraid after most recent update (4/22/2023)

### ISSUE THREAD

**Issue by Stuke00** [nicolargo/glances#2354] opened 2023-04-22 21:07 UTC
**Describe the bug**
Glances is not launching

**To Reproduce**
1. Installed Glances on Unraid from Community Applications

**Expected behavior**
Expecting Glances to launch without error. 

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Unraid 6.11.5
 - Glances Version [output of glances -V] Glances v3.3.1.1 with PsUtil v5.9.4
Log file: /tmp/glances-root.log
 - Glances logs file [output of tail -10 <glances logs file>]
```
 - 2023-04-22 21:03:36,512 -- WARNING -- Missing Python Lib (No module named 'netifaces'), IP plugin is disabled
2023-04-22 21:03:36,526 -- WARNING -- Sparklines module not found (No module named 'sparklines')
2023-04-22 21:03:36,527 -- WARNING -- Missing Python Lib (No module named 'pymdstat'), Raid plugin is disabled
2023-04-22 21:03:36,537 -- WARNING -- Missing Python Lib (No module named 'pySMART'), HDD Smart plugin is disabled
2023-04-22 21:03:36,539 -- WARNING -- Missing Python Lib (No module named 'wifi'), Wifi plugin is disabled
2023-04-22 21:03:36,539 -- WARNING -- Wifi lib is not compliant with Python 3, Wifi plugin is disabled
2023-04-22 21:05:58,757 -- INFO -- Start Glances 3.3.1.1
2023-04-22 21:05:58,757 -- INFO -- CPython 3.10.9 (/usr/bin/python3) and psutil 5.9.4 detected
2023-04-22 21:06:06,047 -- INFO -- Start Glances 3.3.1.1
2023-04-22 21:06:06,047 -- INFO -- CPython 3.10.9 (/usr/bin/python3) and psutil 5.9.4 detecte
```
 - Glances test [output of glances --issue] (only available with Glances 3.1.7 or higher)
```
text  error  warn  system  array  login  

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/docker/api/client.py", line 268, in _raise_for_status
    response.raise_for_status()
  File "/usr/lib/python3.10/site-packages/requests/models.py", line 1021, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 404 Client Error: Not Found for url: http+docker://localhost/v1.41/images/ef426329691401f733a8b97a0ab616ea3a211144aeb7f540d8e451bdf8cc550c/json

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3.10/site-packages/glances/__main__.py", line 19, in <module>
    glances.main()
  File "/usr/lib/python3.10/site-packages/glances/__init__.py", line 179, in main
    start(config=core.get_config(), args=core.get_args())
  File "/usr/lib/python3.10/site-packages/glances/__init__.py", line 108, in start
    mode = GlancesMode(config=config, args=args)
  File "/usr/lib/python3.10/site-packages/glances/webserver.py", line 31, in __init__
    self.stats.update()
  File "/usr/lib/python3.10/site-packages/glances/stats.py", line 216, in update
    self._plugins[p].update()
  File "/usr/lib/python3.10/site-packages/glances/plugins/glances_plugin.py", line 1114, in wrapper
    ret = fct(self, *args, **kw)
  File "/usr/lib/python3.10/site-packages/glances/plugins/glances_plugin.py", line 1131, in wrapper
    ret = fct(*args, **kw)
  File "/usr/lib/python3.10/site-packages/glances/plugins/glances_docker.py", line 255, in update
    container_stats['Image'] = container.image.tags
  File "/usr/lib/python3.10/site-packages/docker/models/containers.py", line 40, in image
    return self.client.images.get(image_id.split(':')[1])
  File "/usr/lib/python3.10/site-packages/docker/models/images.py", line 335, in get
    return self.prepare_model(self.client.api.inspect_image(name))
  File "/usr/lib/python3.10/site-packages/docker/utils/decorators.py", line 19, in wrapped
    return f(self, resource_id, *args, **kwargs)
  File "/usr/lib/python3.10/site-packages/docker/api/image.py", line 251, in inspect_image
    return self._result(
  File "/usr/lib/python3.10/site-packages/docker/api/client.py", line 274, in _result
    self._raise_for_status(response)
  File "/usr/lib/python3.10/site-packages/docker/api/client.py", line 270, in _raise_for_status
    raise create_api_error_from_http_exception(e) from e
  File "/usr/lib/python3.10/site-packages/docker/errors.py", line 39, in create_api_error_from_http_exception
    raise cls(e, response=response, explanation=explanation) from e
docker.errors.ImageNotFound: 404 Client Error for http+docker://localhost/v1.41/images/ef426329691401f733a8b97a0ab616ea3a211144aeb7f540d8e451bdf8cc550c/json: Not Found ("no such image: ef426329691401f733a8b97a0ab616ea3a211144aeb7f540d8e451bdf8cc550c: No such image: sha256:ef426329691401f733a8b97a0ab616ea3a211144aeb7f540d8e451bdf8cc550c")
```
**Additional context**

**Comment by RazCrimson** [comment] 2023-04-23 11:03
@Stuke00 
Could you tell the exact version of glances installed?

The latest release of glances (v3.3.1.1) was on January 14th. No releases were made after that.

This issue seems to be a duplicate of https://github.com/nicolargo/glances/issues/2233 which is already fixed in the latest develop branch. Stable release with these changes would be in June on `v3.4.0`

**Comment by Stuke00** [comment] 2023-04-23 11:34
![image](https://user-images.githubusercontent.com/16128402/233837218-61234fe0-f5c4-48d7-bff5-338fc7629733.png)
 Looks like the docker image was updated.  https://hub.docker.com/r/nicolargo/glances/ 

It looks like I was using whatever tag was default, but when I specified nicolargo/glances:latest instead of just nicolargo/glances then it started working.  But the default unraid template is just nicolargo/glances which is the one that isn't working.

**Comment by RazCrimson** [comment] 2023-04-23 12:13
Without a explicit tag, the normal behavior is to use `latest` tag (so `nicolargo/glances` -> `nicolargo/glances:latest`)

The docker image tags with the `dev` suffix run off the latest develop branch which should probably used for the time mentioned there.

Anyways, the above mentioned issue would be fixed in the next release. 

Closing the issue as there are no problems

**Closed by RazCrimson** 2023-04-23 12:13 UTC
Labels: duplicated
