### ISSUE TITLE
WebUI - Infinite loading

### ISSUE THREAD

**Issue by wblondel** [nicolargo/glances#934] opened 2016-09-29 13:55 UTC
Hi,

When I open the WebUI, it never loads. I only see the 3 dots.

The Chrome console shows

```
vendor.js:2 TypeError: _.padLeft is not a function
    at setData (main.js:1)
    at getPlugin (main.js:1)
    at i.getData.then.e.is_disconnected (main.js:1)
    at u (vendor.js:3)
    at vendor.js:3
    at d.$eval (vendor.js:3)
    at d.$digest (vendor.js:3)
    at d.$apply (vendor.js:3)
    at s (vendor.js:2)
    at b (vendor.js:2)
```

every 2 seconds.

#### Versions

* Glances (glances -V): 2.7.1
* PSutil (glances -V): 4.3.1
* Operating System (lsb_release -a): Debian GNU/Linux 8.6 (jessie)

**Comment by nicolargo** [comment] 2016-09-29 20:08
Can you try hit *CTRL-F5* to clear your Chrome cache ?

**Comment by MrPom** [comment] 2016-09-30 09:02
Same problem for me (with same config), clearing Chrome cache didn’t help btw.

**Comment by wblondel** [comment] 2016-09-30 09:23
Clearing the cache didn't help. However if I restart the server there is a
chance that it works again.

**Comment by nicolargo** [comment] 2016-09-30 09:25
Can **not** reproduce on my system:

- Ubuntu 16.04 or CentOS 7.2
- Chrome 53.0.2785.116 (64-bit)
- Firefox 45.1.0
- Glances 2.7

**Comment by wblondel** [comment] 2016-09-30 09:28
Chrome was 53.0.2785.116 (64-bit), now it's 53.0.2785.143 (64-bit) because it updated.

I'll try with Firefox when I'm back home :)

Thanks for the help

**Comment by MrPom** [comment] 2016-09-30 09:40
Config :

- Debian GNU/Linux 8.6 (jessie)
- Chrome 53.0.2785.143 (64-bit)
- Firefox 49.0

Chrome error :

```
TypeError: _.padLeft is not a function
    at setData (main.js:1)
    at getPlugin (main.js:1)
    at i.getData.then.e.is_disconnected (main.js:1)
    at u (vendor.js:formatted:3974)
    at vendor.js:formatted:3984
    at d.$eval (vendor.js:formatted:4471)
    at d.$digest (vendor.js:formatted:4399)
    at d.$apply (vendor.js:formatted:4498)
    at s (vendor.js:formatted:2979)
    at b (vendor.js:formatted:3078)(anonymous function) @ vendor.js:formatted:3558(anonymous function) @ vendor.js:formatted:2729u @ vendor.js:formatted:3977(anonymous function) @ vendor.js:formatted:3984$eval @ vendor.js:formatted:4471$digest @ vendor.js:formatted:4399$apply @ vendor.js:formatted:4498s @ vendor.js:formatted:2979b @ vendor.js:formatted:3078_.onload @ vendor.js:formatted:3101
```

Firefox error :


```
Error: _.padLeft is not a function
this.setData@http://xxx.xxx.xxx.xxx:61208/js/main.js:1:8848
this.getPlugin@http://xxx.xxx.xxx.xxx:61208/js/main.js:1:8379
e.refreshData/<@http://xxx.xxx.xxx.xxx:61208/js/main.js:1:2690
u@http://xxx.xxx.xxx.xxx:61208/js/vendor.js:3:4592
a/<@http://xxx.xxx.xxx.xxx:61208/js/vendor.js:3:4764
Sn/this.$get</d.prototype.$eval@http://xxx.xxx.xxx.xxx:61208/js/vendor.js:3:12405
Sn/this.$get</d.prototype.$digest@http://xxx.xxx.xxx.xxx:61208/js/vendor.js:3:10887
Sn/this.$get</d.prototype.$apply@http://xxx.xxx.xxx.xxx:61208/js/vendor.js:3:12690
s@http://xxx.xxx.xxx.xxx:61208/js/vendor.js:2:19086
b@http://xxx.xxx.xxx.xxx:61208/js/vendor.js:2:21015
Ve/</_.onload@http://xxx.xxx.xxx.xxx:61208/js/vendor.js:2:21487
    vendor.js:2:29330
    o/<()vendor.js:2
    xe/this.$get</<()vendor.js:2
    u()vendor.js:3
    a/<()vendor.js:3
    Sn/this.$get</d.prototype.$eval()vendor.js:3
    Sn/this.$get</d.prototype.$digest()vendor.js:3
    Sn/this.$get</d.prototype.$apply()vendor.js:3
```

**Comment by notFloran** [comment] 2016-09-30 16:36
I confirm the bug, the problem appears when there are alerts.

I will fix this.

**Comment by nclsHart** [comment] 2016-09-30 19:06
This bug should be already fixed in develop by this commit 82b05c35f83fe8a43a91647a653aab9e98eadbb4.

**Comment by nicolargo** [comment] 2016-10-01 07:29
@wblondel / @MrPom : can you test the DEVELOP branch ?

**Comment by marcwaz** [comment] 2016-10-04 04:14
Hello,
I have used your docker container (so the latest develop branch I suppose..) and I encounter the same issue (stay on loading page). The chrome error is different for me:
vendor.js:13920 TypeError: Cannot read property 'push' of undefined
    at main.js:1202
    at vendor.js:37576
    at Function.forIn (vendor.js:45444)
    at setData (main.js:1182)
    at getPlugin (main.js:492)
    at GlancesStats.getData.then.$scope.is_disconnected (main.js:220)
    at processQueue (vendor.js:16383)
    at vendor.js:16399
    at Scope.$eval (vendor.js:17682)
    at Scope.$digest (vendor.js:17495)

**Comment by marcwaz** [comment] 2016-10-04 04:33
[glances.zip](https://github.com/nicolargo/glances/files/507696/glances.zip)

You will also find in attachment my glances.log file (generated in debug mode). You will noticed several issues inside. Hope it helps !

**Comment by nicolargo** [comment] 2016-10-04 09:33
@nclsHart Another look ?

**Comment by marcwaz** [comment] 2016-10-04 11:00
No. It's exactly the same under Chrome and IE. 
I see the logo and the 3 dots. I'm waiting but nothing is coming.. Even if I refresh with Ctrl+F5.

**Comment by nclsHart** [comment] 2016-10-04 19:52
This is not the same bug, this one seems to come from the raid plugin.

@marcwaz Could you send us the result of `curl http://localhost:61208/api/2/raid`.

Meanwhile the bug fix, you should be able to bypass this issue by running glances with the `--disable-raid` argument.

**Comment by marcwaz** [comment] 2016-10-04 23:44
Here is the result of the API call:
{"md2": {"status": "active", "available": "2", "used": "2", "components": {"sdb2": "1", "sda2": "0"}, "config": "UU", "type": "raid1"}, "md1": {"status": "active", "available": "2", "used": "2", "components": {"sdb1": "1", "sda1": "0"}, "config": "UU", "type": "raid1"}}

The option --disable-raid doesn't fix the issue. 

Did you notice the 4 following relevant errors in the log file ?
1 - SystemV: Error while executing service ([Errno 2] No such file or directory)
2 - ports: Error while pinging host ([Errno 2] No such file or directory)
3 - Cannot grab block IO usage for container e0975165117dbd2fcac5151aad01685e05f119a4e689546924eefbcb6aff1930 (list index out of range)
4 - Cannot grab CPU/IO/MEM... usage for container 

To conclude, I have played with all you "disable option":
--disable-cpu --disable-mem --disable-swap --disable-load --disable-network --disable-ip --disable-diskio --disable-fs --disable-folder --disable-irq --disable-sensors --disable-hddtemp --disable-raid --disable-docker --disable-ports --disable-amps --disable-log --disable-bold --disable-bg -2 -3 -4 -5
The problem remains the same and I keep always the same js error !

**Comment by marcwaz** [comment] 2016-10-05 00:52
My conclusion is that indeed the pb comes from the disk information, even if the --disable-raid doesn't fix it.
In order that you understand my hard disk config, here is the result of the lsblk command:
NAME    MAJ:MIN RM   SIZE RO TYPE  MOUNTPOINT
sda       8:0    0 447.1G  0 disk
├─sda1    8:1    0  19.5G  0 part
│ └─md1   9:1    0  19.5G  0 raid1 /
├─sda2    8:2    0 426.6G  0 part
│ └─md2   9:2    0 426.6G  0 raid1 /eSolution
└─sda3    8:3    0  1023M  0 part  [SWAP]
sdb       8:16   0 447.1G  0 disk
├─sdb1    8:17   0  19.5G  0 part
│ └─md1   9:1    0  19.5G  0 raid1 /
├─sdb2    8:18   0 426.6G  0 part
│ └─md2   9:2    0 426.6G  0 raid1 /eSolution
└─sdb3    8:19   0  1023M  0 part  [SWAP]

**Comment by marcwaz** [comment] 2016-10-11 23:13
Hello, any news about this issue ? Do you need more information in order to solve it ?

**Comment by maxpower47** [comment] 2016-10-16 20:37
I'm getting the same error as @marcwaz.  It looks like it traces back to https://github.com/nicolargo/glances/commit/483fa29cfa9cec0ffa0adc746dfd097a9e1e7089, which upgraded lodash from 3.10.1 to 4.13.1.  The `forIn` method apparently changed from taking a third argument to specify the "this" context (https://lodash.com/docs/3.10.1#forIn) to not being able to (https://lodash.com/docs/4.16.4#forIn).  As a result, `this` on this line https://github.com/nicolargo/glances/blob/2b80fa041694f4bddc192d6491512dc5d54bb9db/glances/outputs/static/js/services/plugins/glances_raid.js#L29 refers to `Window` rather than to the service object, so `this.disks` in undefined.

**Comment by nicolargo** [comment] 2016-10-21 20:03
@nclsHart / @notFloran : Can you have a look on this issue and propose a patch. @maxpower47 has identified the problem in its lastest comment (https://github.com/nicolargo/glances/issues/934#issuecomment-254072988). Thanks in advance !

**Comment by notFloran** [comment] 2016-10-22 07:36
I have made a PR to fix the bug : #941

**Comment by nicolargo** [comment] 2016-10-22 08:48
Merged ! Thanks @notFloran :)

@marcwaz / @maxpower47 : Please can you test the DEVELOP branch ?

**Comment by marcwaz** [comment] 2016-10-22 11:01
Test done. I confirm that now it works ;-). Thx!

**Comment by nicolargo** [comment] 2016-10-22 11:29
Perfect ! Thanks to all !

**Closed** 2016-10-22 11:29 UTC
Labels: bug
