### ISSUE TITLE
Sensors plugin error: IOError: [Errno 5] Input/output error

### ISSUE THREAD

**Issue by nrapopor** [nicolargo/glances#1079] opened 2017-04-09 01:08 UTC
##### Issue
* This just started happening all of a sudden. I was running glances as a service in the export and quiet mode `glances --export-influxdb -q` and all of a sudden the service failed (after a day or so an could not be brought back up. This looks like some kind of regression since there were already open bugs on this behavior in older versions   
   ````log
    2017-04-08 20:04:09,362 -- INFO -- Start Glances 2.9.1
    2017-04-08 20:04:09,362 -- INFO -- CPython 2.7.12+ and PSutil 5.2.1 detected
    2017-04-08 20:04:09,368 -- INFO -- Read configuration file '/etc/glances/glances.conf'
    2017-04-08 20:04:09,373 -- INFO -- Start GlancesStandalone mode
    2017-04-08 20:04:09,502 -- CRITICAL -- Error while initializing the sensors plugin ([Errno 5] Input/output error)
    2017-04-08 20:04:09,503 -- ERROR -- Traceback (most recent call last):
      File "/usr/local/lib/python2.7/dist-packages/glances/stats.py", line 105, in _load_plugin
        self._plugins[name] = plugin.Plugin(args=args)
      File "/usr/local/lib/python2.7/dist-packages/glances/plugins/glances_sensors.py", line 53, in __init__
        self.glancesgrabsensors = GlancesGrabSensors()
      File "/usr/local/lib/python2.7/dist-packages/glances/plugins/glances_sensors.py", line 231, in __init__
        self.stemps = psutil.sensors_temperatures()
      File "/usr/local/lib/python2.7/dist-packages/psutil/__init__.py", line 2212, in sensors_temperatures
        rawdict = _psplatform.sensors_temperatures()
      File "/usr/local/lib/python2.7/dist-packages/psutil/_pslinux.py", line 1116, in sensors_temperatures
        current = float(cat(base + '_input')) / 1000.0
      File "/usr/local/lib/python2.7/dist-packages/psutil/_pslinux.py", line 299, in cat
        return f.read().strip()
     IOError: [Errno 5] Input/output error

     2017-04-08 20:04:09,536 -- INFO -- Stats will be exported to InfluxDB server: http://localhost:8086
     2017-04-08 20:04:09,911 -- INFO -- Quiet mode is ON: Nothing will be displayed
  ````
* output of the service 
  ```log
    ● glances.service - Glances
      Loaded: loaded (/etc/systemd/system/glances.service; enabled; vendor preset: enabled)
      Active: failed (Result: exit-code) since Sat 2017-04-08 20:04:12 EDT; 35min ago
    Main PID: 31234 (code=exited, status=1/FAILURE)

    Apr 08 20:04:12 P870KM1G glances[31234]:   File "/usr/local/lib/python2.7/dist-packages/glances/standalone.py", line 119, in serve_forever
    Apr 08 20:04:12 P870KM1G glances[31234]:     self.end()
    Apr 08 20:04:12 P870KM1G glances[31234]:   File "/usr/local/lib/python2.7/dist-packages/glances/standalone.py", line 127, in end
    Apr 08 20:04:12 P870KM1G glances[31234]:     self.stats.end()
    Apr 08 20:04:12 P870KM1G glances[31234]:   File "/usr/local/lib/python2.7/dist-packages/glances/stats.py", line 268, in end
    Apr 08 20:04:12 P870KM1G glances[31234]:     self._plugins[p].exit()
    Apr 08 20:04:12 P870KM1G glances[31234]: AttributeError: 'dict' object has no attribute 'exit'
    Apr 08 20:04:12 P870KM1G systemd[1]: glances.service: Main process exited, code=exited,status=1/FAILURE
    Apr 08 20:04:12 P870KM1G systemd[1]: glances.service: Unit entered failed state.
    Apr 08 20:04:12 P870KM1G systemd[1]: glances.service: Failed with result 'exit-code'.
  ````

* The output of sensors `LANG=c sensors -u` is 
  ````log
    coretemp-isa-0000
    Adapter: ISA adapter
    Physical id 0:
      temp1_input: 71.000
      temp1_max: 80.000
      temp1_crit: 100.000
      temp1_crit_alarm: 0.000
    Core 0:
      temp2_input: 71.000
      temp2_max: 80.000
      temp2_crit: 100.000
      temp2_crit_alarm: 0.000
    Core 1:
      temp3_input: 71.000
      temp3_max: 80.000
      temp3_crit: 100.000
      temp3_crit_alarm: 0.000
    Core 2:
      temp4_input: 56.000
      temp4_max: 80.000
      temp4_crit: 100.000
      temp4_crit_alarm: 0.000
    Core 3:
      temp5_input: 56.000
      temp5_max: 80.000
      temp5_crit: 100.000
      temp5_crit_alarm: 0.000

    acpitz-virtual-0
    Adapter: Virtual device
    temp1:
      temp1_input: 71.000
      temp1_crit: 120.000

    iwlwifi-virtual-0
     Adapter: Virtual device
     temp1:
    ERROR: Can't get value of subfeature temp1_input: I/O error
  ````
* The output of the `LANG=c acpi -V` 
  ````log
    Battery 0: Full, 100%
    Battery 0: design capacity 5900 mAh, last full capacity 5730 mAh = 97%
    Adapter 0: on-line
    Thermal 0: ok, 68.0 degrees C
    Thermal 0: trip point 0 switches to mode critical at temperature 120.0 degrees C
    Cooling 0: Processor 0 of 3
    Cooling 1: Processor 0 of 3
    Cooling 2: Processor 0 of 3
    Cooling 3: Processor 0 of 3
    Cooling 4: x86_pkg_temp no state information available
    Cooling 5: LCD 0 of 100
    Cooling 6: Processor 0 of 3
    Cooling 7: intel_powerclamp no state information available
    Cooling 8: Processor 0 of 3
    Cooling 9: Processor 0 of 3
    Cooling 10: iwlwifi no state information available
    Cooling 11: Processor 0 of 3
    Cooling 12: iwlwifi 0 of 19

  ````
* Running with `--disable-sensors` is ignored 
   ````bash
   $glances -q --export-influxdb --disable-sensors
    Error while initializing the sensors plugin ([Errno 5] Input/output error)
    Exception in thread Thread-17:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
        self.run()
      File "/usr/lib/python2.7/threading.py", line 754, in run
        self.__target(*self.__args, **self.__kwargs)
      File "/usr/local/lib/python2.7/dist-packages/glances/exports/glances_export.py", line 153, in update
        all_stats = stats.getAllExportsAsDict(plugin_list=self.plugins_to_export())
      File "/usr/local/lib/python2.7/dist-packages/glances/stats.py", line 225, in getAllExportsAsDict
        return {p: self._plugins[p].get_export() for p in plugin_list}
      File "/usr/local/lib/python2.7/dist-packages/glances/stats.py", line 225, in <dictcomp>
        return {p: self._plugins[p].get_export() for p in plugin_list}
    AttributeError: 'dict' object has no attribute 'get_export'

    Traceback (most recent call last):
      File "/usr/local/bin/glances", line 11, in <module>
        load_entry_point('Glances==2.9.1', 'console_scripts', 'glances')()
      File "/usr/local/lib/python2.7/dist-packages/glances/__init__.py", line 134, in main
        start(config=config, args=args)
      File "/usr/local/lib/python2.7/dist-packages/glances/__init__.py", line 103, in start
        mode.serve_forever()
      File "/usr/local/lib/python2.7/dist-packages/glances/standalone.py", line 119, in serve_forever
        self.end()
      File "/usr/local/lib/python2.7/dist-packages/glances/standalone.py", line 127, in end
        self.stats.end()
      File "/usr/local/lib/python2.7/dist-packages/glances/stats.py", line 268, in end
        self._plugins[p].exit()
    AttributeError: 'dict' object has no attribute 'exit'
   ````

#### Versions

* Glances (glances -V): Glances v2.9.1
* PSutil (glances -V):  psutil v5.2.1
* Operating System (lsb_release -a): 
        Distributor ID:	Ubuntu
        Description:	Ubuntu 16.10
        Release:  	16.10
        Codename:	yakkety

#### Logs

You can also pastebin the Glances logs file (https://glances.readthedocs.io/en/latest/config.html#logging)

**Comment by nicolargo** [comment] 2017-04-09 07:59
Hi, can not reproduce on my Ubuntu 16.04 system...

Please can you start Glances in debug mode (-d option) with the sensors plugin enable and [paste/bin](https://pastebin.com/) us the result of the Glances configuration file. I want to focus on the following lines (| grep sensors):

```
2017-04-09 09:57:53,436 -- DEBUG -- Available plugins list: ['load', 'docker', 'help', 'ip', 'memswap', 'processlist', 'cloud', 'uptime', 'network', 'percpu', 'irq', 'system', 'diskio', 'gpu', 'folders', 'core', 'fs', 'raid', 'mem', 'alert', 'psutilversion', 'hddtemp', 'sensors', 'now', 'quicklook', 'wifi', 'cpu', 'processcount', 'amps', 'batpercent', 'ports']
2017-04-09 09:57:53,457 -- DEBUG -- Load limit: sensors_temperature_core_careful = 60.0
2017-04-09 09:57:53,457 -- DEBUG -- Load limit: sensors_temperature_core_warning = 70.0
2017-04-09 09:57:53,457 -- DEBUG -- Load limit: sensors_temperature_core_critical = 80.0
2017-04-09 09:57:53,458 -- DEBUG -- Load limit: sensors_temperature_hdd_careful = 45.0
2017-04-09 09:57:53,458 -- DEBUG -- Load limit: sensors_temperature_hdd_warning = 52.0
2017-04-09 09:57:53,458 -- DEBUG -- Load limit: sensors_temperature_hdd_critical = 60.0
2017-04-09 09:57:53,458 -- DEBUG -- Load limit: sensors_battery_careful = 80.0
2017-04-09 09:57:53,458 -- DEBUG -- Load limit: sensors_battery_warning = 90.0
2017-04-09 09:57:53,458 -- DEBUG -- Load limit: sensors_battery_critical = 95.0
2017-04-09 09:57:53,527 -- DEBUG -- Plugin sensors update return [{'key': 'label', 'type': 'temperature_core', 'unit': 'C', 'value': 27, 'label': 'acpitz 1'}, {'key': 'label', 'type': 'temperature_core', 'unit': 'C', 'value': 29, 'label': 'acpitz 2'}, {'key': 'label', 'type': 'temperature_core', 'unit': 'C', 'value': 63, 'label': 'Physical id 0'}, {'key': 'label', 'type': 'temperature_core', 'unit': 'C', 'value': 60, 'label': 'Core 0'}, {'key': 'label', 'type': 'temperature_core', 'unit': 'C', 'value': 63, 'label': 'Core 1'}, {'key': 'label', 'type': 'temperature_core', 'unit': 'C', 'value': 63, 'label': 'CPU'}, {'key': 'label', 'type': 'temperature_core', 'unit': 'C', 'value': 48, 'label': 'Ambient'}, {'key': 'label', 'type': 'temperature_core', 'unit': 'C', 'value': 45, 'label': 'SODIMM'}, {'key': 'label', 'type': 'battery', 'unit': '%', 'value': 78, 'label': 'Battery'}]
2017-04-09 09:57:53,822 -- DEBUG -- Plugin sensors update return [{'key': 'label', 'type': 'temperature_core', 'unit': 'C', 'value': 27, 'label': 'acpitz 1'}, {'key': 'label', 'type': 'temperature_core', 'unit': 'C', 'value': 29, 'label': 'acpitz 2'}, {'key': 'label', 'type': 'temperature_core', 'unit': 'C', 'value': 63, 'label': 'Physical id 0'}, {'key': 'label', 'type': 'temperature_core', 'unit': 'C', 'value': 60, 'label': 'Core 0'}, {'key': 'label', 'type': 'temperature_core', 'unit': 'C', 'value': 63, 'label': 'Core 1'}, {'key': 'label', 'type': 'temperature_core', 'unit': 'C', 'value': 64, 'label': 'CPU'}, {'key': 'label', 'type': 'temperature_core', 'unit': 'C', 'value': 48, 'label': 'Ambient'}, {'key': 'label', 'type': 'temperature_core', 'unit': 'C', 'value': 45, 'label': 'SODIMM'}, {'key': 'label', 'type': 'battery', 'unit': '%', 'value': 78, 'label': 'Battery'}]
2017-04-09 09:57:54,077 -- DEBUG -- Export sensors stats to InfluxDB
2017-04-09 09:57:56,836 -- DEBUG -- Plugin sensors update return [{'key': 'label', 'type': 'temperature_core', 'unit': 'C', 'value': 27, 'label': 'acpitz 1'}, {'key': 'label', 'type': 'temperature_core', 'unit': 'C', 'value': 29, 'label': 'acpitz 2'}, {'key': 'label', 'type': 'temperature_core', 'unit': 'C', 'value': 63, 'label': 'Physical id 0'}, {'key': 'label', 'type': 'temperature_core', 'unit': 'C', 'value': 60, 'label': 'Core 0'}, {'key': 'label', 'type': 'temperature_core', 'unit': 'C', 'value': 63, 'label': 'Core 1'}, {'key': 'label', 'type': 'temperature_core', 'unit': 'C', 'value': 64, 'label': 'CPU'}, {'key': 'label', 'type': 'temperature_core', 'unit': 'C', 'value': 48, 'label': 'Ambient'}, {'key': 'label', 'type': 'temperature_core', 'unit': 'C', 'value': 45, 'label': 'SODIMM'}, {'key': 'label', 'type': 'battery', 'unit': '%', 'value': 78, 'label': 'Battery'}]
2017-04-09 09:57:57,024 -- DEBUG -- Stop the sensors plugin
2017-04-09 09:57:57,027 -- DEBUG -- Stop the sensors plugin
```

**Comment by giampaolo** [comment] 2017-04-09 09:49
This (`IOError: [Errno 5] Input/output error`) looks like a bug with the Linux kernel. I think psutil should skip the error so that it can at least show the other sensors. I'll open a bug for that.

**Comment by giampaolo** [comment] 2017-04-09 09:50
https://github.com/giampaolo/psutil/issues/1009

**Comment by giampaolo** [comment] 2017-04-09 15:31
OK, I fixed this in psutil (master branch). 
@nicolargo RuntimeWarning is now raised in such a case. There are also other places in psutil code in which RuntimeWarning may be raised. How does Glances deal with warnings? Are they printed on screen?

**Comment by nicolargo** [comment] 2017-04-09 20:14
Hi @giampaolo thanks for the PsUtil patch. Concerning the warnings, Glances use the default behavior (print message on console). I will have a look if it is possible to redirect it to a warning message in the log file.

**Comment by nrapopor** [comment] 2017-04-09 22:55
Sorry for the n00b question (I'm not a python guy) -- I pulled the master from giampaolo/psutil and built it (v5.2.2) however glances is still pointing to 5.2.1 ... What am i doing wrong?

**Comment by nrapopor** [comment] 2017-04-10 16:57
Never mind I RTFMed the answer. Like I said not a python guy -- just starting to get used to it. 

this was run with:

  ````console
    uname -a
    Linux P870KM1G 4.8.0-46-generic #49-Ubuntu SMP Fri Mar 31 13:57:14 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux

    glances -V
    Glances v2.9.1 with psutil v5.2.2
 ````
 ````console
    /usr/local/bin/glances -d -q --export-influxdb
    Error while initializing the sensors plugin ([Errno 5] Input/output error)
    Exception in thread Thread-17:
    Traceback (most recent call last):
      File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
        self.run()
      File "/usr/lib/python2.7/threading.py", line 754, in run
        self.__target(*self.__args, **self.__kwargs)
      File "/usr/local/lib/python2.7/dist-packages/glances/exports/glances_export.py", line 153, in update
        all_stats = stats.getAllExportsAsDict(plugin_list=self.plugins_to_export())
      File "/usr/local/lib/python2.7/dist-packages/glances/stats.py", line 225, in getAllExportsAsDict
        return {p: self._plugins[p].get_export() for p in plugin_list}
      File "/usr/local/lib/python2.7/dist-packages/glances/stats.py", line 225, in <dictcomp>
        return {p: self._plugins[p].get_export() for p in plugin_list}
    AttributeError: 'dict' object has no attribute 'get_export'

    Traceback (most recent call last):
      File "/usr/local/bin/glances", line 11, in <module>
        load_entry_point('Glances==2.9.1', 'console_scripts', 'glances')()
      File "/usr/local/lib/python2.7/dist-packages/glances/__init__.py", line 134, in main
        start(config=config, args=args)
      File "/usr/local/lib/python2.7/dist-packages/glances/__init__.py", line 103, in start
        mode.serve_forever()
      File "/usr/local/lib/python2.7/dist-packages/glances/standalone.py", line 119, in serve_forever
        self.end()
      File "/usr/local/lib/python2.7/dist-packages/glances/standalone.py", line 127, in end
        self.stats.end()
      File "/usr/local/lib/python2.7/dist-packages/glances/stats.py", line 268, in end
        self._plugins[p].exit()
    AttributeError: 'dict' object has no attribute 'exit'
  ````

The pastebin of the log : https://pastebin.com/7b0KZ3Xg 

Thanks,

Nick

**Comment by nrapopor** [comment] 2017-04-21 19:14
Hi all,

Sorry for bandwidth – I’ve tried the fixed psutil … no luck – I’ve posted the debug level results to the case.
Any thoughts?

Thanks,

Nick

**Comment by giampaolo** [comment] 2017-04-21 19:16
Looks like the latest errors are related to glances, not psutil, so the upgrade of psutil solved at least the first original issue (I/O Error).

**Comment by nrapopor** [comment] 2017-04-21 19:19
Thanks … Will wait for an update from @nicolargo

**Comment by nrapopor** [comment] 2017-05-22 21:30
Any thoughts, I did provide the additional info you were asking for (see above comment from from April 10th )

**Comment by nicolargo** [comment] 2018-02-14 21:41
I close this issue because the root issue is solved (thanks to the PsUtil upgrade). 

Please feel free to open another issue for the second one.

**Closed by nicolargo** 2018-02-14 21:41 UTC
Labels: needs more info
